### ISSUE TITLE
Latest plugin release does not include `lifetime` property

### ISSUE THREAD

**Issue by RasmusEthon** [buildkite-plugins/gcp-workload-identity-federation-buildkite-plugin#5]
## Problem 
After some debugging of the released version 1.0.0 I found out that the source code does not include the `lifetime` plugin configuration property even though the release was published much later than the functionality was added to the codebase. Right now the README file and the only release are out of sync which will lead to confusion for anybody trying to use the plugin.

Would it be possible to release a new minor version from main that adds the support to it? 

## Reproduce
Download the release source code (which Buildkite will also use) and verify that the source code doesn't have the property and the `pre-command.sh` doesn't contain the functionality.

**Comment by pzeballos** [comment]
Hey @RasmusEthon! you are correct and that change didn't make it to the last release. We'll do a new one this week

**Comment by RasmusEthon** [comment]
Thank you @pzeballos, looking forward to the release!

**Comment by pzeballos** [comment]
Released [v1.1.0](https://github.com/buildkite-plugins/gcp-workload-identity-federation-buildkite-plugin/releases/tag/v1.1.0)

Thanks @RasmusEthon!
